In [1]:
import pandas as pd
pd.DataFrame({'Yes': [50, 21], 'No': [131, 2]})

   Yes   No
0   50  131
1   21    2

In [3]:
pd.DataFrame({'Bob': ['I liked it.', 'It wad awful'], 'Sue': ['Pretty', 'Bland']})

            Bob     Sue
0   I liked it.  Pretty
1  It wad awful   Bland

In [15]:
pd.DataFrame({
    'A':['a','ab','aa'],
    'B':['b','ba','bb']},
    index=['resultA', 'resultB','resultC'])

          A   B
resultA   a   b
resultB  ab  ba
resultC  aa  bb

In [16]:
pd.Series([1,2,3,4,5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [19]:
df = pd.read_csv('data.csv')

In [20]:
df.shape

(3, 3)

In [21]:
df.head()

   title     name  age
0    abc    test1   17
1   abcd   test12   18
2  abcde  test123   19